LOGGER_NAME = "main"

KEY_OUTPUT_FOLDER = "OUTFOLDER"
VALUE_OUTPUT_FOLDER_DEFAULT = ""

KEY_SEED = "SEED"
VALUE_SEED_DEFAULT = 0

KEY_WIDTH = "WIDTH"
VALUE_WIDTH_DEFAULT = 512

KEY_HEIGHT = "HEIGHT"
VALUE_HEIGHT_DEFAULT = 512

KEY_GUIDANCE_SCALE = "GUIDANCE_SCALE"
VALUE_GUIDANCE_SCALE_DEFAULT = 15.0

KEY_STEPS = "STEPS"
VALUE_STEPS_DEFAULT = 100

KEY_SCHEDULER = "SCHEDULER"
VALUE_SCHEDULER_DEFAULT = "Default"
VALUE_SCHEDULER_DPM_SOLVER_MULTISTEP = "DPMSolverMultistepScheduler"
VALUE_SCHEDULER_LMS_DISCRETE = "LMSDiscreteScheduler"
VALUE_SCHEDULER_EULER_DISCRETE = "EulerDiscreteScheduler"
VALUE_SCHEDULER_PNDM = "PNDMScheduler"
VALUE_SCHEDULER_DDIM = "DDIMScheduler"

KEY_PREVIEW = "PREVIEW"
VALUE_PREVIEW_DEFAULT = True
